services:
  postgres:
    image: postgres:15
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./kanban-BE
      dockerfile: Dockerfile
    image: kanban-backend:1.2
    container_name: kanban-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: kanban
      DB_PASSWORD: kanban
      DB_NAME: kanban

  frontend:
    build:
      context: ./kanban
      dockerfile: Dockerfile
    image: kanban-frontend:1.0
    container_name: kanban-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
